# Generated by Django 5.0.3 on 2024-04-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_name_customer_first_name_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.CharField(max_length=10),
        ),
    ]
