# Generated by Django 5.0.3 on 2024-04-24 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_customer_pincode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='lastName',
        ),
    ]
