# Generated by Django 5.0.3 on 2024-04-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='apartment',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
