# Generated by Django 5.0.3 on 2024-04-25 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_customer_apartment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
