# Generated by Django 5.0.3 on 2024-04-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_customer_state_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='emails',
            field=models.EmailField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
